# App Properties
app.name=Sentria
app.device-name=My PC

# Monitoring Properties
monitoring.enabled=true
monitoring.interval-seconds=10

# Notifications & ntfy Properties
notifications.provider=ntfy
notifications.ntfy.enabled=true
notifications.ntfy.server-url=https://ntfy.sh
notifications.ntfy.topic=sentria-demo-topic


# Storage / Smartctl Settings
storage.smartctl.enabled=true
storage.smartctl.command=smartctl
storage.smartctl.device=/dev/nvme0n1

# Spring Datasource (SQLite)
spring.datasource.url=jdbc:sqlite:./data/sentria.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Flyway Migrations
spring.flyway.enabled=true
spring.flyway.url=jdbc:sqlite:./data/sentria.db
spring.flyway.locations=classpath:db/migration


spring.ai.openai.api-key="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"